name Latest blog post workflow and snake generated

on
  schedule
      # every Monday
    - cron '0 0 * * 1'

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch
  push {branches [main]}

jobs

    update-readme-with-blog
        name Update this repo's README with latest blog posts
        runs-on ubuntu-latest
        steps
            - uses actionscheckout@v2
            #- uses  gautamkrishnarblog-post-workflow@v1
              #with
                #feed_list httpsdev.tofeed@elbrag
      # Snake Animation
            - uses Platanesnk@master
              id snake-gif

              with
                github_user_name deep-matter
                svg_out_path distgithub-contribution-grid-snake.svg
            - uses crazy-maxghaction-github-pages@v2.1.3
              with
                target_branch output
                build_dir dist
              env
                GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}